### ISSUE TITLE
As a user, I want a pointer positioned for every tracked pose

### ISSUE THREAD

**Issue by LabOfOz** [LabOfOz/SeeClarke#16]
This story should only deal with calculating the values, and the actual drawing of the cursors should be left up to the user.

### Tasks
**Part A:**
- [ ] Copy/Paste prototype code from our other project: https://github.com/UseAnything/UseAnything--old/blob/4f4db643e36e2932ee9361042ec12899ba8dd99e/src/components/Pointer.vue#L81-L161

**Part B:**
- [ ] Accurately calculate (X, Y)
- [ ] Accurately calculate distance from camera (Z)
- [ ] Accurately calculate angles
